#!/bin/bash
echo Installing fingerprint libs...
sudo apt install fprintd libpam-fprintd
echo Enabling fingerprint authentication...
sudo pam-auth-update --enable fprintd
#echo Adding fingerprint...
#fprintd-enroll --finger right-index-finger